app/controllers/bookings_controller.rb
app/controllers/reviews_controller.rb
app/views/layouts/application.html.erb
config/initializers/assets.rb

Added code inside bookings and reviews controllers

Added bookings and reviews controllers

---

db/seeds.rb

Added a seed file to clean database and generate some instances for testing

Generated instance of User and Flat

---

app/models/review.rb
db/seeds.rb

validates was mispelled in one model so there was a conflict with db:seed

Mispelling found in model corrected

---

app/controllers/bookings_controller.rb
app/controllers/reviews_controller.rb
app/views/bookings/new.html.erb
app/views/reviews/new.html.erb

Added forms for creating new bookings and new reviews and updated the user variable to current_user in their respective controllers

Added #new views for booking and review

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

Added each members' github link on the footer. Different hover colors for each. Feel free to change.

Added links to team's github on footer

---

app/views/layouts/application.html.erb

Replaced # with the correct paths in the navbar

Added links to navbar buttons

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Added a background image and some small styling to home page

Added some styling on home page

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Added big register button in homepage

Added register button in homepage

---

app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb

rails g devise:views auto-generated the views for User

Generated user views using devise

---

app/controllers/flats_controller.rb
app/models/flat.rb
app/views/flats/index.html.erb
app/views/flats/new.html.erb
app/views/flats/show.html.erb

Fixed delete action in index and show views.

fixed delete actions in different views

---

app/views/pages/home.html.erb

Adds if statement in homepage to check if logged in

Changes welcome message if visitor

---

app/views/layouts/application.html.erb

Before I forget from the flashcards the helper "user_signed_in?", I added it to the navbar

Updated navbar links

---

app/assets/stylesheets/pages/_about.scss
app/controllers/flats_controller.rb

Added gradient to bg... not satisfied yet

Made pretty

---

db/seeds.rb

added 4 seeds

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/pages/about.html.erb

Customized UI with clickable links, user, and redirection to GitHub pages.

customized ui

---

app/controllers/bookings_controller.rb
app/policies/booking_policy.rb
app/policies/flat_policy.rb
app/views/flats/show.html.erb

Added authorization for booking

Fixed the errors with bookings controller/views

---

app/views/bookings/show.html.erb

created bookings show view

---

app/controllers/bookings_controller.rb
app/views/bookings/show.html.erb
config/routes.rb

Created bookings controller show action + displayed some values in the view

Created bookings controller show action

---

app/controllers/flats_controller.rb
app/policies/flat_policy.rb
app/views/layouts/application.html.erb

implemented search logic - until multiple columns

---

Gemfile
Gemfile.lock
app/controllers/flats_controller.rb
app/models/flat.rb
app/policies/flat_policy.rb
app/views/layouts/application.html.erb

Improve search bar

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/flats/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
db/migrate/20230315213637_add_last_name_to_users.rb
db/migrate/20230315213920_remove_first_name_from_users.rb
db/migrate/20230315214000_add_first_name_to_users.rb
db/schema.rb
db/seeds.rb

Added first and last names on:
- seed
- model
- controller
- views

Added user first and last names

---

app/controllers/bookings_controller.rb
app/controllers/reviews_controller.rb
app/models/flat.rb
app/models/user.rb
app/policies/review_policy.rb
app/views/bookings/index.html.erb
app/views/bookings/show.html.erb
app/views/flats/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/migrate/20230315224015_add_comment_to_reviews.rb
db/schema.rb
db/seeds.rb

Added review features and a booking index page with user's bookings

Added review

---

app/views/bookings/index.html.erb
app/views/bookings/show.html.erb

Changed date format

---

app/views/bookings/show.html.erb
app/views/devise/registrations/new.html.erb
app/views/flats/show.html.erb
app/views/users/show.html.erb

Added host full name and email

Added other info on booking confirmation page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/javascript/controllers/map_controller.js
app/views/flats/index.html.erb

modified the footer and small details
